version: '3.5'
services:
    postgres:
        image: postgres:12
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    web:
        depends_on:
            "postgres":
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"